#!/usr/bin/python

import os
import sys

# Check for PEP 8 conformance
toolsPath = os.path.dirname(os.path.realpath(__file__)) + '/../tools'
res = os.system(toolsPath + '/run-pep8')
if res != 0:
   sys.exit(1)
