#!/usr/bin/python

import os
import sys

# Check for PEP 8 conformance
basePath = os.path.dirname(os.path.realpath(__file__)) + '/..'
res = os.system('cd ' + basePath + ' && make flake8')
if res != 0:
   sys.exit(1)
