#!/bin/bash

cat << EOF
#========================================
# _azurectl
#----------------------------------------
function _azurectl {
    local cur prev opts
    _get_comp_words_by_ref cur prev

    if [ \$COMP_CWORD -eq 1 ]; then
        __comp_reply "compute --version --help --config --account"
    elif [ \$COMP_CWORD -eq 2 ]; then
        case "\$prev" in
            "compute")
                __comp_reply "storage image"
                ;;
            *)
                ;;
        esac
    elif [ \$COMP_CWORD -eq 3 ]; then
        case "\$prev" in
            "storage")
                __comp_reply "upload delete account container"
                ;;
            "image")
                __comp_reply "list"
                ;;
            *)
                ;;
        esac
    elif [ \$COMP_CWORD -eq 4 ]; then
        case "\$prev" in
            "container")
                __comp_reply "list show"
                ;;
            "account")
                __comp_reply "list"
                ;;
            "upload")
                __comp_reply "--max-chunk-size --container"
                ;;
            "delete")
                __comp_reply "--container"
                ;;
            *)
                ;;
        esac
    elif [ \$COMP_CWORD -eq 5 ]; then
        case "\$prev" in
            "show")
                __comp_reply "--container"
                ;;
            *)
                ;;
        esac
    fi
    return 0
}

#========================================
# comp_reply
#----------------------------------------
function __comp_reply {
    word_list=\$@
    COMPREPLY=(\$(compgen -W "\$word_list" -- \${cur}))
}

complete -F _azurectl -o default azurectl
EOF
